version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.local
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3000"
    command: "yarn dev"
